# Use official Node image
FROM node:22 AS base

# Set working directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy source files
COPY . .

# Expose dev port
EXPOSE 3000

# Start with nodemon
CMD ["npm", "run", "dev"]
